main: games.indigo.skooblock.SkooBlock
name: Skooblock
description: A fully fledged, feature rich custom Skyblock experience!
version: ${project.version}
api-version: 1.14
authors:
- TheMGRF

commands:
  island:
    aliases: [is]
    description: Base Skyblock command
  skooblock:
    aliases: [sb]
    description: Base Admin Skyblock command