main: games.indigo.skooblock.Main
name: Skooblock
description: A fully fledged, feature rich custom Skyblock experience!
version: 0.0.1
api-version: 1.13
authors:
- TheMGRF

commands:
  island:
    aliases: [is]
    description: Base Skyblock command